model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  loss_type: 'B'
  gamma: 1000
  max_capacity: 50
  Capacity_max_iter: 10000

data_params:
  data_path: "D:/LaureaMagistrale/PrimoAnno/Secondo_Semestre/DeepLearning/datasets/CelebA"
  train_batch_size: 256
  val_batch_size:  128
  patch_size: 64
  num_workers: 0
  
exp_params:
  LR: 0.009
  weight_decay: 0.003
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 42

trainer_params:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 10
  max_time: '00:02:30:00'

training_params:
  tune_lr: False
  tune_batch_size: False
  lr_min: 0.005
  lr_max: 1
  resume_train: False
  ckpt_path: null
  patience: 5
  every_n_epochs: 1

logging_params:
  enable_wandb: True
  save_dir: "logs/"
  manual_seed: 42
  name: "BetaVAE"