model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  data_path: "D:/LaureaMagistrale/PrimoAnno/Secondo_Semestre/DeepLearning/datasets/CelebA"
  train_batch_size: 32
  val_batch_size: 64
  test_batch_size: 64
  patch_size: 64
  num_workers: 0

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 5
  max_time: '00:00:03:00'

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: "VanillaVAE"